name: Flutter Pagstar CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main


jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: flutter pub get

    - name: Test
      run: flutter test
