name: Flutter Pagstar CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      env:
        GIT_SSH_COMMAND: 'ssh -i ${{ secrets.SSH_PRIVATE_KEY }}'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Test
      run: flutter test
