name: Flutter Pagstar CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      
    - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Test
      run: flutter test
